In [58]:
import pandas as pd
import numpy as np

In [19]:
data = {
    'Имя': ['Анна', 'Борис', 'Виктор', 'Мария'],
    'Возраст': [25, 30, 35, 28],
    'Город': ['Москва', 'СПб', 'Казань', 'Москва'],
    'Зарплата': [50000, 60000, 70000, 55000]
}
df = pd.DataFrame(data)
df

      Имя  Возраст   Город  Зарплата
0    Анна       25  Москва     50000
1   Борис       30     СПб     60000
2  Виктор       35  Казань     70000
3   Мария       28  Москва     55000

In [65]:
data = [
    ['Анна', 25, 'Москва', 50000],
    ['Борис', 30, 'СПб', 60000],
    ['Виктор', 35, 'Казань', 70000],
    ['Мария', 28, 'Москва']
]
columns = ['Имя', 'Возраст', 'Город', 'Зарплата']

df_1 = pd.DataFrame(data, columns=columns)
df_1

      Имя  Возраст   Город  Зарплата
0    Анна       25  Москва   50000.0
1   Борис       30     СПб   60000.0
2  Виктор       35  Казань   70000.0
3   Мария       28  Москва       NaN

In [114]:
# Чтение CSV
df = pd.read_csv(r"e:\users\galbinskiy_va\Desktop\КубГУ\dg dq\git_materials\dg_dq_course\lesson_3\data.csv", sep=';')
df

,ID,ФИО,Возраст,Курс,Факультет,Средний_балл,Форма_обучения
0,1,Иванов Иван Иванович,19,2,Информатика,4.5,Бюджет
1,2,Петрова Анна Сергеевна,20,3,Экономика,4.8,Бюджет
2,3,Сидоров Петр Алексеевич,18,1,Математика,3.9,Контракт
3,4,Козлова Мария Дмитриевна,21,4,Физика,4.2,Бюджет
4,5,Смирнов Алексей Викторович,22,4,Информатика,4.1,Контракт
5,6,Васильева Елена Павловна,19,2,Экономика,4.7,Бюджет
6,7,Морозов Денис Сергеевич,20,3,Математика,3.5,Контракт
7,8,Волкова Татьяна Андреевна,18,1,Физика,4.9,Бюджет
8,9,Павлов Артем Николаевич,21,3,Информатика,4.3,Контракт
9,10,Николаева Ольга Игоревна,22,4,Экономика,4.6,Бюджет

In [20]:
# Первые 5 строк
df.head()

      Имя  Возраст   Город  Зарплата
0    Анна       25  Москва     50000
1   Борис       30     СПб     60000
2  Виктор       35  Казань     70000
3   Мария       28  Москва     55000

In [21]:
# Последние 3 строки
df.tail(3)

      Имя  Возраст   Город  Зарплата
1   Борис       30     СПб     60000
2  Виктор       35  Казань     70000
3   Мария       28  Москва     55000

In [22]:
# Информация о DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Имя       4 non-null      object
 1   Возраст   4 non-null      int64
 2   Город     4 non-null      object
 3   Зарплата  4 non-null      int64
dtypes: int64(2), object(2)
memory usage: 256.0+ bytes

In [23]:
# Основные статистики
df.describe()

         Возраст      Зарплата
count   4.000000      4.000000
mean   29.500000  58750.000000
std     4.203173   8539.125638
min    25.000000  50000.000000
25%    27.250000  53750.000000
50%    29.000000  57500.000000
75%    31.250000  62500.000000
max    35.000000  70000.000000

In [24]:
# Размер DataFrame
print(f"Размер: {df.shape}") # (строки, столбцы)

Размер: (4, 4)

In [25]:
print(f"Столбцы: {df.columns.tolist()}")

Столбцы: ['Имя', 'Возраст', 'Город', 'Зарплата']

In [ ]:
# Один столбец (возвращает Series)
df['Возраст']
df.Возраст # точечная нотация

0    25
1    30
2    35
3    28
Name: Возраст, dtype: int64

In [29]:
df[['Имя', 'Зарплата']]

      Имя  Зарплата
0    Анна     50000
1   Борис     60000
2  Виктор     70000
3   Мария     55000

In [30]:
# По индексу
df.iloc[0] # первая строка

Имя           Анна
Возраст         25
Город       Москва
Зарплата     50000
Name: 0, dtype: object

In [31]:
df.iloc[1:3] # строки 1 и 2

      Имя  Возраст   Город  Зарплата
1   Борис       30     СПб     60000
2  Виктор       35  Казань     70000

In [32]:
# По условию
mask = df['Возраст'] > 30
df[mask]

      Имя  Возраст   Город  Зарплата
2  Виктор       35  Казань     70000

In [33]:
# Комбинированные условия
mask = (df['Возраст'] > 25) & (df['Город'] == 'Москва')
df[mask]

     Имя  Возраст   Город  Зарплата
3  Мария       28  Москва     55000

In [41]:
# Проверка на пропуски
print(df_bad.isnull().sum())
print('\n\n\n')
# Визуализация пропусков
print(df_bad.isnull())

Имя         0
Возраст     1
Город       1
Зарплата    0
dtype: int64




     Имя  Возраст  Город  Зарплата
0  False    False  False     False
1  False    False  False     False
2  False     True  False     False
3  False    False   True     False

In [39]:
data = {
    'Имя': ['Анна', 'Борис', 'Виктор', 'Мария'],
    'Возраст': [25, 30, None, 28],
    'Город': ['Москва', 'СПб', 'Казань', None],
    'Зарплата': [50000, 60000, 70000, 55000]
}
df_bad = pd.DataFrame(data)
df_bad

      Имя  Возраст   Город  Зарплата
0    Анна     25.0  Москва     50000
1   Борис     30.0     СПб     60000
2  Виктор      NaN  Казань     70000
3   Мария     28.0    None     55000

In [40]:
df_bad.dropna()

     Имя  Возраст   Город  Зарплата
0   Анна     25.0  Москва     50000
1  Борис     30.0     СПб     60000

In [44]:
df_bad.fillna({
'Возраст': df['Возраст'].mean(),
'Город': 'Неизвестно'
})

      Имя  Возраст       Город  Зарплата
0    Анна     25.0      Москва     50000
1   Борис     30.0         СПб     60000
2  Виктор     29.5      Казань     70000
3   Мария     28.0  Неизвестно     55000

In [ ]:
print(f"среднее =    {df['Зарплата'].mean()}")
print(f"медиана =    {df['Зарплата'].median()}")
print(f"отклонение = {df['Зарплата'].std()}")
print(f"минимум =    {df['Зарплата'].min()}")
print(f"максимум =   {df['Зарплата'].max()}")

среднее =    58750.0
медиана =    57500.0
отклонение = 8539.125638299665
минимум =    50000
максимум =   70000

In [49]:
# Группировка по городу
grouped = df.groupby('Город')
grouped

In [51]:
# Средняя зарплата по городам
grouped['Зарплата'].mean()

Город
Казань    70000.0
Москва    52500.0
СПб       60000.0
Name: Зарплата, dtype: float64

In [52]:
# Несколько агрегаций
grouped['Зарплата'].agg(['mean', 'count', 'std'])

           mean  count          std
Город
Казань  70000.0      1          NaN
Москва  52500.0      2  3535.533906
СПб     60000.0      1          NaN

In [56]:
# Группировка по нескольким столбцам
df.groupby(['Город', 'Возраст']).agg({'Зарплата': 'mean'})

                Зарплата
Город  Возраст
Казань 35        70000.0
Москва 25        50000.0
       28        55000.0
СПб    30        60000.0

In [57]:
# Новый столбец
df['Премия'] = df['Зарплата'] * 0.1
df

      Имя  Возраст   Город  Зарплата  Премия
0    Анна       25  Москва     50000  5000.0
1   Борис       30     СПб     60000  6000.0
2  Виктор       35  Казань     70000  7000.0
3   Мария       28  Москва     55000  5500.0

In [59]:
# Столбец на основе условия
df['Статус'] = np.where(df['Возраст'] > 30, 'Старший', 'Младший')
df

      Имя  Возраст   Город  Зарплата  Премия   Статус
0    Анна       25  Москва     50000  5000.0  Младший
1   Борис       30     СПб     60000  6000.0  Младший
2  Виктор       35  Казань     70000  7000.0  Старший
3   Мария       28  Москва     55000  5500.0  Младший

In [61]:
# Применение функции
df['Имя_длина'] = df['Имя'].apply(len)
df

      Имя  Возраст   Город  Зарплата  Премия   Статус  Имя_длина
0    Анна       25  Москва     50000  5000.0  Младший          4
1   Борис       30     СПб     60000  6000.0  Младший          5
2  Виктор       35  Казань     70000  7000.0  Старший          6
3   Мария       28  Москва     55000  5500.0  Младший          5

In [ ]:
df['Зарплата'] = df['Зарплата'] * 1.1
df

      Имя  Возраст   Город  Зарплата  Премия   Статус  Имя_длина
0    Анна       25  Москва   55000.0  5000.0  Младший          4
1   Борис       30     СПб   66000.0  6000.0  Младший          5
2  Виктор       35  Казань   77000.0  7000.0  Старший          6
3   Мария       28  Москва   60500.0  5500.0  Младший          5

In [ ]:
# Сохранение в CSV
df.to_csv('processed_data.csv', index=False, encoding='utf-8')

In [ ]:
# Загрузите данные из CSV файла
# Выведите первые 5 строк
# Выведите информацию о DataFrame (info)
# Выведите основные статистические характеристики (describe)

In [70]:
df = pd.read_csv(r"e:\users\galbinskiy_va\Desktop\КубГУ\dg dq\git_materials\dg_dq_course\lesson_3\taxi.csv", sep=',')

In [73]:
df.describe()

       trip_cost_rub  temperature_c  precipitation_mm
count      10.000000      10.000000         10.000000
mean      954.000000      18.800000          2.320000
std       549.832298       3.425395          3.678103
min       330.000000      14.000000          0.000000
25%       575.000000      16.250000          0.000000
50%       825.000000      18.500000          0.100000
75%      1257.500000      21.500000          3.675000
max      2100.000000      24.000000         10.100000

In [75]:
# Сколько всего строк и столбцов в датасете?
# Какие столбцы присутствуют в данных и их типы?
# Есть ли пропущенные значения в каждом столбце?
df.shape

(10, 8)

In [79]:
df.isnull().sum()

full_name            0
tariff_class         0
trip_cost_rub        0
pickup_location      0
dropoff_location     0
weather_condition    0
temperature_c        0
precipitation_mm     0
dtype: int64

In [ ]:
# Найдите всех пассажиров бизнесс класса

df[df['tariff_class'] == 'Бизнес']

,full_name,tariff_class,trip_cost_rub,pickup_location,dropoff_location,weather_condition,temperature_c,precipitation_mm
2,Сидоров Петр Алексеевич,Бизнес,1500,ул. Тверская 15,"Бизнес-центр ""Москва""",Дождь,15,4.5
8,Григорьев Артем Павлович,Бизнес,1350,"Гостиница ""Центральная""","Аэропорт ""Внуково""",Ясно,23,0.0

In [ ]:
df.query(" weather_condition == 'Дождь' ").weather_condition.count()

2

In [108]:
all_trip_cnt = df['tariff_class'].count()

df_tarif = pd.DataFrame(df.groupby('tariff_class')['tariff_class'].count())

df_tarif['share'] = df_tarif['tariff_class']/all_trip_cnt

df_tarif

              tariff_class  share
tariff_class
Бизнес                   2    0.2
Детский                  1    0.1
Комфорт                  3    0.3
Минивэн                  1    0.1
Эконом                   3    0.3

In [107]:
pd.DataFrame(df_tarif)

              tariff_class
tariff_class
Бизнес                   2
Детский                  1
Комфорт                  3
Минивэн                  1
Эконом                   3